---
swagger: "2.0"
info:
  description: "iotregistry on hyperledger"
  version: "1.0.0"
  title: "IOTRegistry api"
host: "localhost:8082"
basePath: "/v1"
schemes:
- "http"
produces:
- "application/json"
paths:
  /registerOwner:
    post:
      summary: "register owner name"
      description: "register owner name to ledger"
      operationId: "ownerNamePOST"
      parameters:
      - name: "OwnerName"
        in: "query"
        description: "Name of owner"
        required: true
        type: "string"
        format: "text"
      - name: "Pubkey"
        in: "query"
        description: "Public key of owner"
        required: true
        type: "string"
        format: "text"
      - name: "Signature"
        in: "query"
        description: "Sig of name and data"
        required: true
        type: "string"
        format: "text"
      - name: "Data"
        in: "query"
        description: "data for registerOwner"
        required: true
        type: "string"
        format: "text"
      responses:
        200:
          description: ""
          schema:
            type: "boolean"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "iotregistryware"

  /registerThing:
    post:
      summary: "thing"
      description: "register thing"
      operationId: "thingPOST"
      parameters:
      - name: "Nonce"
        in: "query"
        description: "Nonce for thing"
        required: true
        type: "string"
        format: "text"
      - name: "Identities"
        in: "query"
        description: "alternate identites of thing owner"
        required: true
        type: "array"
        items:
          type: "string"
        collectionFormat: "csv"
      - name: "OwnerName"
        in: "query"
        description: "name of thing owner"
        required: true
        type: "string"
        format: "text"
      - name: "Signature"
        in: "query"
        description: "sig of nonce + identities + data + spec"
        required: true
        type: "string"
        format: "text"
      - name: "Data"
        in: "query"
        description: "thing data"
        required: true
        type: "string"
        format: "text"
      - name: "Spec"
        in: "query"
        description: "spec for thing"
        required: true
        type: "string"
        format: "text"  
      responses:
        200:
          description: ""
          schema:
            type: "boolean"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "iotregistryware"

  /registerSpec:
    post:
      summary: "register spec"
      description: "register specification to ledger"
      operationId: "specPOST"
      parameters:
      - name: "SpecName"
        in: "query" 
        description: "name of specification"
        required: true
        type: "string"
        format: "text"
      - name: "OwnerName"
        in: "query"
        description: "name of spec owner"
        required: true
        type: "string"
        format: "text" 
      - name: "Signature"
        in: "query"
        description: "sig of owner name + data"
        required: true
        type: "string"
        format: "text"
      - name: "Data"
        in: "query"
        description: "specification data"
        required: true
        type: "string"
        format: "text"
      responses:
        200:
          description: "result"
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "iotregistryware"


  /owner:
    get:
      summary: "owner"
      description: "get owner info"
      operationId: "ownerGET"
      parameters:
      - name: "OwnerName"
        in: "query"
        description: "name of owner"
        required: true
        type: "string"
        format: "text"
      responses:
        200:
          description: "owner info"
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "iotregistryware"
  /thing:
    get:
      summary: "thing"
      description: "get thing info"
      operationId: "thingGET"
      parameters:
      - name: "ThingNonce"
        in: "query"
        description: "Nonce of thing"
        required: true
        type: "string"
        format: "text"
        
      responses:
        200:
          description: "thing info"
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "iotregistryware"
  /spec:
    get:
      summary: "spec"
      description: "get spec info"
      operationId: "specGET"
      parameters:
      - name: "SpecName"
        in: "query"
        description: "Name of spec"
        required: true
        type: "string"
        format: "text"
      responses:
        200:
          description: "spec info"
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "iotregistryware"

  /generateRegisterNameSig:
    post:
      summary: "generate signature for registerName"
      description: "generate signature for registerName"
      operationId: "generateRegisterNameSigPOST"
      parameters:
      - name: "OwnerName"
        in: "query"
        description: "name of owner"
        required: true
        type: "string"
        format: "text"
      - name: "Data"
        in: "query"
        description: ""
        required: true
        type: "string"
        format: "text"
      - name: "PrivateKeyStr"
        in: "query"
        description: "owner private key as string"
        required: true
        type: "string"
        format: "text"
      responses:
        200:
          description: "Signature"
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Utility"

  /generateRegisterThingSig:
    post:
      summary: "generate signature for registerThing"
      description: "generate signature for registerThing"
      operationId: "generateRegisterThingSigPOST"
      parameters:
      - name: "OwnerName"
        in: "query"
        description: "name of owner"
        required: true
        type: "string"
        format: "text"
      - name: "Identities"
        in: "query"
        description: "identities of thing owner"
        required: true
        type: "array"
        items:
          type: "string"
      - name: "Spec"
        in: "query"
        description: "spec info"
        required: true
        type: "string"
        format: "text"
      - name: "Data"
        in: "query"
        description: "thing info"
        required: true
        type: "string"
        format: "text"
      - name: "PrivateKeyStr"
        in: "query"
        description: "owner private key as string"
        required: true
        type: "string"
        format: "text"
      responses:
        200:
          description: "Signature"
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Utility"
  /generateRegisterSpecSig:
    post:
      summary: "generate signature for registerSpec"
      description: "generate signature for registerSpec"
      operationId: "generateRegisterSpecSigPOST"
      parameters:
      - name: "SpecName"
        in: "query"
        description: "name of spec"
        required: true
        type: "string"
        format: "text"
      - name: "OwnerName"
        in: "query"
        description: "name of owner"
        required: true
        type: "string"
        format: "text"
      - name: "Data"
        in: "query"
        description: ""
        required: true
        type: "string"
        format: "text"
      - name: "PrivateKeyStr"
        in: "query"
        description: "owner private key as string"
        required: true
        type: "string"
        format: "text"
      responses:
        200:
          description: "Signature"
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Utility"
      
definitions:
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      fields:
        type: "string"
