---
swagger: "2.0"
info:
  description: "iotregistry on hyperledger"
  version: "1.0.0"
  title: "IOTRegistry api"
host: "localhost:8082"
basePath: "/v1"
schemes:
- "http"
produces:
- "application/json"
paths:
  /registrant:
    post:
      summary: "create registrant"
      description: " "
      operationId: "registrantPOST"
      parameters:
      - name: "RegistrantName"
        in: "query"
        description: "Name of registrant"
        required: true
        type: "string"
        format: "text"
      - name: "RegistrantPubkey"
        in: "query"
        description: "Public key of registrant"
        required: true
        type: "string"
        format: "text"
      - name: "Signature"
        in: "query"
        description: "Sig of name and data"
        required: true
        type: "string"
        format: "text"
      - name: "Data"
        in: "query"
        description: "data for registerOwner"
        required: true
        type: "string"
        format: "text"
      responses:
        200:
          description: ""
          schema:
            type: "boolean"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "iotregistryware"
    get:
      summary: "registrant"
      description: "get registrant info"
      operationId: "registrantGET"
      parameters:
      - name: "RegistrantPubkey"
        in: "query"
        description: "name of registrant"
        required: true
        type: "string"
        format: "text"
      responses:
        200:
          description: "registrant info"
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "iotregistryware"
  /registerThing:
    post:
      summary: "thing"
      description: "register thing"
      operationId: "thingPOST"
      parameters:
      - name: "Nonce"
        in: "query"
        description: "Nonce for thing"
        required: true
        type: "string"
        format: "text"
      - name: "Aliases"
        in: "query"
        description: "alternate identites of thing registrant"
        required: true
        type: "array"
        items:
          type: "string"
        collectionFormat: "csv"
      - name: "RegistrantPubkey"
        in: "query"
        description: "name of thing registrant"
        required: true
        type: "string"
        format: "text"
      - name: "Signature"
        in: "query"
        description: "sig of ownerName + identities + data + spec"
        required: true
        type: "string"
        format: "text"
      - name: "Data"
        in: "query"
        description: "thing data"
        required: true
        type: "string"
        format: "text"
      - name: "Spec"
        in: "query"
        description: "spec for thing"
        required: true
        type: "string"
        format: "text"  
      responses:
        200:
          description: ""
          schema:
            type: "boolean"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "iotregistryware"

  /registerSpec:
    post:
      summary: "register spec"
      description: "register specification to ledger"
      operationId: "specPOST"
      parameters:
      - name: "SpecName"
        in: "query" 
        description: "name of specification"
        required: true
        type: "string"
        format: "text"
      - name: "RegistrantPubkey"
        in: "query"
        description: "name of spec registrant"
        required: true
        type: "string"
        format: "text" 
      - name: "Signature"
        in: "query"
        description: "sig of registrant name + data"
        required: true
        type: "string"
        format: "text"
      - name: "Data"
        in: "query"
        description: "specification data"
        required: true
        type: "string"
        format: "text"
      responses:
        200:
          description: "result"
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "iotregistryware"

  /thing:
    get:
      summary: "thing"
      description: "get thing info"
      operationId: "thingGET"
      parameters:
      - name: "Alias"
        in: "query"
        description: "Nonce of thing"
        required: true
        type: "string"
        format: "text"
        
      responses:
        200:
          description: "thing info"
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "iotregistryware"
  /spec:
    get:
      summary: "spec"
      description: "get spec info"
      operationId: "specGET"
      parameters:
      - name: "SpecName"
        in: "query"
        description: "Name of spec"
        required: true
        type: "string"
        format: "text"
      responses:
        200:
          description: "spec info"
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "iotregistryware"

  /createRegistrantSig:
    post:
      summary: "generate signature for Registrant"
      description: "generate signature for Registrant"
      operationId: "createRegistrantSig"
      parameters:
      - name: "RegistrantName"
        in: "query"
        description: "name of registrant"
        required: true
        type: "string"
        format: "text"
      - name: "RegistrantPubkey"
        in: "query"
        description: "pubkey of registrant"
        required: true
        type: "string"
        format: "text"
      - name: "Data"
        in: "query"
        description: ""
        required: true
        type: "string"
        format: "text"
      - name: "PrivateKeyStr"
        in: "query"
        description: "registrant private key as string"
        required: true
        type: "string"
        format: "text"
      responses:
        200:
          description: "Signature"
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "iotregistryware"

  /generateRegisterThingSig:
    post:
      summary: "generate signature for registerThing"
      description: "generate signature for registerThing"
      operationId: "generateRegisterThingSig"
      parameters:
      - name: "RegistrantPubkey"
        in: "query"
        description: "name of registrant"
        required: true
        type: "string"
        format: "text"
      - name: "Aliases"
        in: "query"
        description: "Aliases of thing registrant"
        required: true
        type: "array"
        items:
          type: "string"
      - name: "Spec"
        in: "query"
        description: "spec info"
        required: true
        type: "string"
        format: "text"
      - name: "Data"
        in: "query"
        description: "thing info"
        required: true
        type: "string"
        format: "text"
      - name: "PrivateKeyStr"
        in: "query"
        description: "registrant private key as string"
        required: true
        type: "string"
        format: "text"
      responses:
        200:
          description: "Signature"
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "iotregistryware"
  /generateRegisterSpecSig:
    post:
      summary: "generate signature for registerSpec"
      description: "generate signature for registerSpec"
      operationId: "generateRegisterSpecSig"
      parameters:
      - name: "SpecName"
        in: "query"
        description: "name of spec"
        required: true
        type: "string"
        format: "text"
      - name: "RegistrantPubkey"
        in: "query"
        description: "name of registrant"
        required: true
        type: "string"
        format: "text"
      - name: "Data"
        in: "query"
        description: ""
        required: true
        type: "string"
        format: "text"
      - name: "PrivateKeyStr"
        in: "query"
        description: "registrant private key as string"
        required: true
        type: "string"
        format: "text"
      responses:
        200:
          description: "Signature"
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "iotregistryware"
      
definitions:
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      fields:
        type: "string"
